### ISSUE TITLE
Link from form / concept to associated phrases

### ISSUE THREAD

**Issue by xrotwang** [clld/tppsr#7]
- A form's details page should show all phrases the form appears in.
- A concept's details page should show all french translations of phrases it appears in or maybe just one like the ["Typical context"](https://wold.clld.org/meaning/1-1#2/24.3/-4.8) in WOLD.

**Comment by xrotwang** [comment]
@lingulist the paper highlights the fact that concepts are elicited in complete phrases - so we might want to be able to provide this context, right?

**Comment by xrotwang** [comment]
The only risk I see is that this may highlight any errors in `etc/phrases.csv`.

**Comment by LinguList** [comment]
The risk is a bliss, I'd say, as it will help us to improve. I like the new solution a lot.
